apiVersion: v1
kind: ConfigMap
metadata:
  name: sre-dummy-tool-config
  namespace: {{ .Values.namespace }}
  annotations:
    team: "SRE"
    slack-channel: "#open-sre"
data:
  dummy.conf: |-
{{ .Files.Get .Values.configFile | indent 4 }}
