apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-manager-deployment
  labels:
    app: vault-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-manager
  template:
    metadata:
      labels:
        app: vault-manager
      annotations:
        sidecar.istio.io/inject: false
    spec:
      containers:
      - name: vault-manager
        image: vault-manager:latest
        ports:
        - containerPort: 1459
