version: '3'
services:
  postgres:
    build:
      context: .
      args:
        - NODE_ENV=local
      dockerfile: docker/postgres.Dockerfile
    container_name: postgres
    ports:
      - "9000:5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=tokenuser
      - POSTGRES_PASSWORD=tokenpass
      - POSTGRES_DB=tokendb
