version: '3'
services:
  postgres:
    build: .
    container_name: postgres
    ports:
      - "9000:5432"
    environment:
      - DEBUG=false
      - DB_USER=postgres
      - DB_PASS=
      - DB_NAME=
      - POSTGRES_PASSWORD=${PSQL_BOX_PASS}
      - POSTGRES_DB=datadb
